name: al_quran_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:

  # network
  dio: 5.8.0+1

  # models generation
  freezed_annotation: 2.4.4
  json_annotation: 4.9.0

  # hive
  hive_flutter: 1.1.0
  hive_generator: 2.0.1

  # cache local storage
  build_runner: 2.4.13

dev_dependencies:
  lints: ^5.0.0
  test: 1.25.15

  # hive
  hive_test: 1.0.1

  # misc
  freezed: 2.5.7
  json_serializable: 6.9.0
