name: run_tests

on:
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-latest

    env:
      # Setup env variables that will be used throughout the workflow
      FLUTTER_VERSION: 3.24.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "${{ env.FLUTTER_VERSION }}"
          channel: stable
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"

      - name: Get Dependencies
        run: flutter pub get

      - name: Analyze
        run: dart analyze --no-fatal-warnings

      - name: Run Tests
        run: flutter test